### ISSUE TITLE
Found BUG with solution

### ISSUE THREAD

**Issue by kint3x** [revk/ESP32-VL53L0X#3]
Hi, during using this library I found you have typoo in init function 

if (v->xshut >= 0)
   {                            // XSHUT or power control
      gpio_set_level (v->xshut, 0);     // Off
      usleep (100000);
      gpio_set_level (v->xshut, 0);     // On
      usleep (10000);           // Plenty of time to boot (data sheet says 1.2ms)
   }
   
You should set log. level 1 in second case, so it will turn on (based on docs).

**Comment by revk** [comment]
Thanks, fixed.
